verion: 2
jobs:
  test:
    working_directory: ~/terraform_aws_v2
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
        name: Init terraform
        command: terraform init ~/terraform_aws_v2
