# 変更不可
variable tags_owner {}
variable tags_env {}
variable ec2_subnet {}
variable rds_subnet {}
variable redshift_subnet {}
variable allow_ip {}
variable public_key_path {}
variable private_key_path {}
variable git_account {}
variable git_pass {}
variable vpc_id {}
variable vpc_cidr_block {}
variable rt_id_public {}
variable rt_id_private {}
variable db_master_password {}
variable resource_stop_flag {}
variable layer_zip {}
variable logical_backup_flag {}
variable "resource_stop_zip" {}
variable "resource_start_zip" {}
variable "ssh_key" {}
variable "join_linux" {}
